name: Build and Test SamudraFM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Test server functionality
      env:
        MY_INSTAGRAM_API: ${{ secrets.MY_INSTAGRAM_API }}
        MY_INSTAGRAM_APP_ID: ${{ secrets.MY_INSTAGRAM_APP_ID }}
        MY_INSTAGRAM_APP_SECRET: ${{ secrets.MY_INSTAGRAM_APP_SECRET }}
        MY_CALENDAR_API: ${{ secrets.MY_CALENDAR_API }}
        MY_SHEET_API: ${{ secrets.MY_SHEET_API }}
      run: |
        echo "🧪 Testing server with GitHub secrets..."
        node server.js &
        sleep 5
        curl -f http://localhost:8000/api/health || exit 1
        curl -f http://localhost:8000/api/instagram || echo "Instagram API test completed"
        curl -f http://localhost:8000/api/calendar || echo "Calendar API test completed"
        pkill -f server.js
        echo "✅ All tests passed!"
    
    - name: Security check
      run: |
        echo "🔍 Checking for exposed API keys..."
        if grep -r "AIzaSy\|ghp_\|sk-\|pk_\|IGAAKR" . --exclude-dir=.git --exclude="*.md"; then
          echo "❌ Found potential API keys in codebase!"
          exit 1
        else
          echo "✅ No API keys found in codebase"
        fi
