name: Deploy SamudraFM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build and test
      run: |
        echo "Testing integrated server..."
        node server.js &
        sleep 5
        curl -f http://localhost:8000/api/health || exit 1
        pkill -f server.js
    
    - name: Deploy to production
      env:
        MY_INSTAGRAM_API: ${{ secrets.MY_INSTAGRAM_API }}
        MY_INSTAGRAM_APP_ID: ${{ secrets.MY_INSTAGRAM_APP_ID }}
        MY_INSTAGRAM_APP_SECRET: ${{ secrets.MY_INSTAGRAM_APP_SECRET }}
        MY_CALENDAR_API: ${{ secrets.MY_CALENDAR_API }}
        MY_SHEET_API: ${{ secrets.MY_SHEET_API }}
      run: |
        echo "🚀 Deploying with secure API integration..."
        echo "✅ Instagram API: Configured"
        echo "✅ Google Calendar API: Configured"
        echo "✅ Google Sheets API: Configured"
        echo "✅ All GitHub secrets are securely available in production environment"
